###
# Copyright (2016-2020) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
---
- hosts: all
  vars:
    - config: "{{ playbook_dir }}/oneview_config.json"
  tasks:
    - name: Gather facts about all Hypervisor Cluster Profiles
      oneview_hypervisor_cluster_profile_facts:
        config: "{{ config }}"
      delegate_to: localhost

    - debug: var=hypervisor_cluster_profiles

    - name: Gather paginated, filtered and sorted facts about Hypervisor Cluster Profiles
      oneview_hypervisor_cluster_profile_facts:
        config: "{{ config }}"
        params:
          start: 0
          count: 3
          sort: 'name:descending'
          filter: 'hypervisorType=Vmware'
    - debug: msg="{{ hypervisor_cluster_profiles | map(attribute='name') | list }}"

    - name: Gather facts about a Hypervisor Cluster Profile by name
      oneview_hypervisor_cluster_profile_facts:
        config: "{{ config }}"
        name: "ClusterProfile"
      delegate_to: localhost

    - debug: var=hypervisor_cluster_profiles

    - name: Gather facts about a Hypervisor Cluster Profile by uri
      oneview_hypervisor_cluster_profile_facts:
        config: "{{ config }}"
        uri: "{{hypervisor_cluster_profiles[0]['uri']}}"
      delegate_to: localhost

    - debug: var=hypervisor_cluster_profiles

    - name: Gather all facts about a Hypervisor Cluster Profile
      oneview_hypervisor_cluster_profile_facts:
        config: "{{ config }}"
        name: "ClusterProfile"
        options:
          - compliancePreview
      delegate_to: localhost

    - debug: var=hypervisor_cluster_profiles
    - debug: var=hypervisor_cluster_profile_compliance_preview
